# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/qwerrty/git/pythonProject/UnlistedSaveDesktop/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(285, 143)
        self.gridLayout = QtWidgets.QGridLayout(LoginForm)
        self.gridLayout.setObjectName("gridLayout")
        self.password_text = QtWidgets.QLabel(LoginForm)
        self.password_text.setObjectName("password_text")
        self.gridLayout.addWidget(self.password_text, 2, 0, 1, 1)
        self.username_text = QtWidgets.QLabel(LoginForm)
        self.username_text.setObjectName("username_text")
        self.gridLayout.addWidget(self.username_text, 1, 0, 1, 1)
        self.pass_edit = QtWidgets.QLineEdit(LoginForm)
        self.pass_edit.setObjectName("pass_edit")
        self.gridLayout.addWidget(self.pass_edit, 2, 1, 1, 1)
        self.login_ui_text = QtWidgets.QLabel(LoginForm)
        self.login_ui_text.setObjectName("login_ui_text")
        self.gridLayout.addWidget(self.login_ui_text, 0, 0, 1, 2)
        self.username_edit = QtWidgets.QLineEdit(LoginForm)
        self.username_edit.setObjectName("username_edit")
        self.gridLayout.addWidget(self.username_edit, 1, 1, 1, 1)
        self.cancel_btn = QtWidgets.QPushButton(LoginForm)
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout.addWidget(self.cancel_btn, 3, 2, 1, 1)
        self.login_btn = QtWidgets.QPushButton(LoginForm)
        self.login_btn.setObjectName("login_btn")
        self.gridLayout.addWidget(self.login_btn, 2, 2, 1, 1)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "LoginForm"))
        self.password_text.setText(_translate("LoginForm", "password"))
        self.username_text.setText(_translate("LoginForm", "username"))
        self.login_ui_text.setText(_translate("LoginForm", "Log in app"))
        self.cancel_btn.setText(_translate("LoginForm", "Cancel"))
        self.login_btn.setText(_translate("LoginForm", "Login"))
